name: Publish NPM package

on:
  push:
    tags:
      - v*.*.*

jobs:
  npm_run_jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm install --only=dev
      - run: npm run jshint
      
  build_and_publish_npm_package:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm install\
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  register_npm_package_with_nodered:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
      - name: Install required packages
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get update -y && sudo apt-get install -y curl httpie python3 python3-pip wget
      - name: Download required scripts into Image
        run: curl -sS -o get_token.py "https://gist.githubusercontent.com/jeroenhendricksen/451db2a595150310b978e793d3843c43/raw/get_token.py"
      - name: Download required scripts into Image
        run: curl -sS -o update_node.sh "https://gist.githubusercontent.com/jeroenhendricksen/db60073cd7ab83f057e5d5b86e981660/raw/update_node.sh"
      - name: Make scripts executable
        run: chmod u+x *.py *.sh
      - name: Print app versions
        run: python3 --version && curl --version
      - name: Run the scripts
        run: ./update_node.sh
